import os
from typing import List, Tuple

VERSION = "v1.0.2"

def get_temp_dirs() -> List[Tuple[str, str, str, bool]]:
    temp_dirs: List[Tuple[str, str, str, bool]] = [
        # Without confirmation (False)
        ("System Temp", os.path.join(os.getenv('SystemRoot', 'C:\\Windows'), 'Temp'), 
            "Temporary system files", False),
        ("User Temp", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Temp'),
            "Temporary user files in Local directory", False),
        ("User Temp", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'LocalLow', 'Temp'),
            "Temporary user files in LocalLow directory", False),
        ("User Cache", os.path.join(os.getenv('USERPROFILE', ''), '.cache'),
            "Cache directory in user directory (.cache)", False),
        ("Internet Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Microsoft', 'Windows', 'INetCache'),
            "Internet Explorer and Edge browser cache", False),
        ("Thumbnail Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Microsoft', 'Windows', 'Explorer'),
            "Thumbnail cache for file explorer (will regenerate on demand)", False),
        ("Crash Dumps", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'CrashDumps'),
            "Application crash dump files", False),
        ("Live Kernel Reports", os.path.join(os.getenv('SystemRoot', 'C:\\Windows'), 'LiveKernelReports'),
            "System diagnostic reports", False),
        ("Event Logs", os.path.join(os.getenv('SystemRoot', 'C:\\Windows'), 'System32', 'winevt', 'Logs'),
            "Windows event log files (system and application logs)", False),
        ("Delivery Optimization", os.path.join(os.getenv('SystemRoot', 'C:\\Windows'), 'SoftwareDistribution', 'DeliveryOptimization'),
            "Windows Update delivery optimization cache", False),
        ("Windows Updates", os.path.join(os.getenv('SystemRoot', 'C:\\Windows'), 'SoftwareDistribution', 'Download'),
            "Windows Update downloads", False),
        ("Windows.old", os.path.join(os.getenv('SystemRoot', 'C:\\Windows'), '..', 'Windows.old'),
            "Previous Windows installation files (removes rollback option)", False),
        ("Spotify Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Spotify', 'Data'),
            "Spotify data cache", False),
        ("Windows Error Reporting", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Microsoft', 'Windows', 'WER'),
            "Windows Error Reporting crash reports", False),
        ("Edge Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Microsoft', 'Edge', 'User Data', 'Default', 'Cache'),
            "Microsoft Edge browser cache", False),
        ("Chrome Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Google', 'Chrome', 'User Data', 'Default', 'Cache'),
            "Google Chrome browser cache", False),
        ("pip Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'pip', 'cache'),
            "Python pip package cache", False),
        ("npm Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'npm-cache'),
            "npm package manager cache", False),
        ("Yarn Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Yarn', 'Cache'),
            "Yarn package manager cache", False),
        ("Visual Studio Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Microsoft', 'VisualStudio'),
            "Visual Studio local cache files", False),
        ("VS Code Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Roaming', 'Code', 'Cache'),
            "Visual Studio Code cache", False),
        ("VS Code Cached Data", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Roaming', 'Code', 'CachedData'),
            "Visual Studio Code cached data", False),
        
        # With confirmation (True)
        ("NVIDIA GL Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'NVIDIA', 'GLCache'),
            "NVIDIA OpenGL cache (may cause temporary shader recompilation)", True),
        ("NVIDIA DX Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'NVIDIA', 'DXCache'),
            "NVIDIA DirectX cache (may cause temporary graphics reload)", True),
        ("Prefetch", os.path.join(os.getenv('SystemRoot', 'C:\\Windows'), 'Prefetch'),
            "System prefetch files (may slow initial program loading if cleared)", True),
        ("Recycle Bin", os.path.join(os.getenv('SystemDrive', 'C:'), '$Recycle.Bin'),
            "Files in the Recycle Bin (permanent deletion)", True),
        ("Gradle Cache", os.path.join(os.getenv('USERPROFILE', ''), '.gradle', 'caches'),
            "Gradle build cache (may require re-downloading dependencies)", True),
        ("Gradle Temp", os.path.join(os.getenv('USERPROFILE', ''), '.gradle', '.tmp'),
            "Gradle temp files (may require re-downloading dependencies)", True),
        ("Windows Logs", os.path.join(os.getenv('SystemRoot', 'C:\\Windows'), 'Logs'),
            "Windows diagnostic and update log files", True),
        ("Discord Cache", os.path.join(os.getenv('APPDATA', ''), 'discord', 'Cache'),
            "Discord application cache", True),
        ("Discord Code Cache", os.path.join(os.getenv('APPDATA', ''), 'discord', 'Code Cache'),
            "Discord code cache", True),
        ("Steam HTML Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Steam', 'htmlcache'),
            "Steam embedded browser cache", True),
        ("Steam Shader Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'Steam', 'shadercache'),
            "Steam shader cache (may recompile shaders)", True),
        ("Epic Games Cache", os.path.join(os.getenv('USERPROFILE', ''), 'AppData', 'Local', 'EpicGamesLauncher', 'Saved', 'webcache'),
            "Epic Games Launcher web cache", True),
        ("Battle.net Cache", os.path.join(os.getenv('PROGRAMDATA', 'C:\\ProgramData'), 'Battle.net', 'Cache'),
            "Battle.net application cache", True),
    ]
    return temp_dirs